### ISSUE TITLE
Don't use TWIG

### ISSUE THREAD

**Issue by chaziz94** [chaziz94/squarebracket#2]
what does it even do, like, literally.

it would look much better if it was made with just php, with no twig shit.

**Comment by forkiesassds** [comment]
Welcome to inconsistency central then!

**Comment by rollerozxa** [comment]
Well, it does a whole lot of things. Twig literally makes HTML injection attacks a thing of the past (and I know you like security), it's more short and concise than PHP's "templating" syntax, it supports layout inheritance and it allows for more code reuse and it's versatile for creating more frontends in the future if you'd ever want that.

It wouldn't look better if we removed Twig, it'd just look like old squareBracket. Probably just as insecure as old squareBracket as well.

So yes, there's a reason as to why we should use Twig. It's secure (it treats all variables as "unsafe" and automatically escapes them unless you explicitly mark them as safe), concise (its liquid-like syntax is shorter and way more appropriate for the context of templating) and fast (with caching enabled there's basically no overhead compared to not using Twig). At least 150 million PHP projects use Twig, based on Packagist's stats. It's not some obscure little thing, it's a major part of modern PHP.

**Comment by chaziz94** [comment]
jesus christ i was stupid

**Comment by PF94** [comment]
lmao i tried to resist

**Comment by PF94** [comment]
@kcielz U Fucked Up Big Time
